<?php

/**
* Implements hook_menu()
*/

function directorio_menu() {
	$items = array();

	$items["directorio"] = array (
		'title' => 'Directorio',
		'description' => 'listado de contactos en el sitio',
		'page callback' => 'directorio_page',        //se va a llamar directorio_page
		'access callback' => 'user_access',					//quito esta linea drupal la pone si no la pongo yo
		'access arguments' => array("Ver directorio"),
		'type' =>  MENU_NORMAL_ITEM //el link lo pone en un menu
		);
		// $items["directorio/buscar"] = array (
		// );
		// $items["directorio/buscar/nombre/%"] = array (
		// );
		// $items["directorio/buscar/Extension/%"] = array (
		// );
	 	$items["contactos/agregar"] = array(
		'title' => 'Agregar Contacto',
		'description' => 'formulario para agregar un contacto',
		'page callback' => 'directorio_agregarContactoform',        //se va a llamar directorio_page
		//'access callback' => 'user_access',					//quito esta linea drupal la pone si no la pongo yo
		'access arguments' => array("Ver contactos"),
		'type' =>  MENU_NORMAL_ITEM, //el link lo pone en un menu
		'page_arguments' => array('directorio_agregarContactoform')
	 	);
		// $items["contactos/ver/%"] = array (
		// );
		// $items["contactos/editar/%"] = array (
		// );
		// $items["eliminar/%"] = array (
		// );
	
	return $items;
	}

/*	
*callback principal de /directorio
*Muestra un listado de contactos en el sitio
*/
function directorio_page(){
	return "Esto es un directorio";
}


function directorio_permission() {
	return array(
			'Ver directorio' => array(
			'title' => t("Ver el directorio de contactos"),
			'description' => t("permite mostrar el directorio de contactos")
			),
			'Ver contactos' => array(
			'title' => t("Ver el directorio de contactos"),
			'description' => t("permite mostrar el directorio de contactos")
		)
	);
}

/**
 *Callback para contactos/Agregar
 *Muestra la forma ara agregar un contacto
*/
function directorio_agregarContactoform($form) {
	$form = array();
	$form["nombre"] = array(
		'#type' => 'textfield',
		'#title' => t("Nombre"),
		'#required' => TRUE,
		'#description' => t("describa el nombre o los nombres del contacto")
		); 
	$form["apellido"] = array(
		'#type' => 'textfield',
		'#title' => t("Apellido Paterno"),
		'#required' => TRUE,
		'#description' => t("Describa el Apellido Paterno")
		);
	$form["materno"] = array(
		'#type' => 'textfield',
		'#title' => t("Apellido Materno"),
		'#required' => FALSE,
		'#description' => t("Describa el Apellido Materno")
		);
	$form["departamento"] = array(
		'#type' => 'select',
		'#title' => t("Departamento"),
		'#required' => TRUE,
		'#description' => t("Seleccione el departamento al que pertence esta persona"),
		'#options' => getDepartamento()
		);
$form["telefono_oficina"] = array(
		'#type' => 'textfield',
		'#title' => t("Teléfono de Oficina"),
		'#required' => TRUE,
		'#description' => t("Escriba el teléfono de oficina"),
		'#options' => _telefonoDeOficinaDefault()
		);
$form["extension_telefonica"] = array(
		'#type' => 'textfield',
		'#title' => t("Extensión Telefonica"),
		'#required' => TRUE,
		'#description' => t("Escriba la extensión telefonica del contacto")
		);
$form["email_trabajo"] = array(
		'#type' => 'textfield',
		'#title' => t("Correo electrónico del trabajo"),
		'#required' => FALSE,
		'#description' => t("Escriba el correo electrónico del trabajo del contacto")
		);
$form["email_personal"] = array(
		'#type' => 'textfield',
		'#title' => t("Correo electrónico personal"),
		'#required' => FALSE,
		'#description' => t("Escriba el correo electrónico personal del contacto")
		);
$form["telefono_casa"] = array(
		'#type' => 'textfield',
		'#title' => t("Teléfono de Casa"),
		'#required' => FALSE,
		'#description' => t("Escriba el teléfono de casa")
		);
$form["telefono_celular"] = array(
		'#type' => 'textfield',
		'#title' => t("Teléfono celular"),
		'#required' => TRUE,
		'#description' => t("Escriba el teléfono celular del contacto")
		);
$form["actions"] = array(
	'#prefix' => '<div class="actions well">',
	'#suffix' => '</div>'
	);
$form["actions"]["submit"] = array(
	'#type' => 'submit',
	'#value' => t("Save")
	);

	return $form;
}

/**
*Submit callback para directorio_agregarContactoForm
**/
function directorio_agregarContactoForm_submit(&$form, &$form_state){

}
/**
*listado de departamento en la compañia
*
*@return array listado de departamentos
*/
function getDepartamento(){
	return array(
		'administracion' => t("Administracion"),
		'recursos_humanos' => t("Recursos Humanos"),
		'sistemas' => t("Sistemas"),
		'ventas' => t("Ventas")
		);
}

/**
*Número de teléfono por default de la organización
*@return string teléfono de oficina por default
*/
function _telefonoDeOficinaDefault() {
	return "2020-7350";
}